# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pOFcTTC4Ulhl7et4KaFiiyvQAzdyrbN
"""

"""
Streamlit app for optimizing & deploying AI models to embedded systems.

Features:
- Upload model (TensorFlow SavedModel / .h5 / .tflite / ONNX)
- Upload sample data (images, CSV, WAV) or simulate serial data
- Build preprocessing pipeline (resize, normalize, mean/std, quantize input)
- Convert/Optimize to TFLite or ONNX (if libs present)
- Simple benchmark (size, inference time over sample inputs)
- Generate deployable bundle (model + preprocessing config + sample embedded code)
"""

import streamlit as st
import tempfile, os, io, time, json, zipfile, shutil
from pathlib import Path
from typing import List, Dict, Any
from PIL import Image
import numpy as np
import base64

# Optional libs (we'll detect at runtime)
try:
    import tensorflow as tf
    TF_AVAILABLE = True
except Exception:
    TF_AVAILABLE = False

try:
    import onnx
    import onnxruntime as ort
    ONNX_AVAILABLE = True
except Exception:
    ONNX_AVAILABLE = False

# Utilities
st.set_page_config(page_title="Embedded AI Model Optimizer & Deployer", layout="wide")

def bytes_to_human(n):
    # returns string like '1.2 MB'
    for unit in ['B','KB','MB','GB','TB']:
        if n < 1024:
            return f"{n:.2f} {unit}"
        n /= 1024
    return f"{n:.2f} PB"

@st.cache_data
def save_uploaded_file(uploaded_file, dst_dir):
    dst = Path(dst_dir) / uploaded_file.name
    with open(dst, "wb") as f:
        f.write(uploaded_file.getbuffer())
    return str(dst)

def read_image_bytes_to_array(b):
    im = Image.open(io.BytesIO(b)).convert('RGB')
    return np.array(im)

# Preprocessing pipeline helper
def apply_preprocessing(img_array: np.ndarray, cfg: Dict[str,Any]) -> np.ndarray:
    # img_array: H x W x C (uint8 or float)
    # cfg: {'resize': (h,w), 'normalize': True/False, 'scale': 1./255, 'mean':[], 'std':[]}
    arr = img_array.astype(np.float32)
    if cfg.get("resize"):
        h,w = cfg["resize"]
        im = Image.fromarray(arr.astype(np.uint8))
        im = im.resize((w,h))
        arr = np.array(im).astype(np.float32)
    if cfg.get("scale"):
        arr = arr * float(cfg["scale"])
    if cfg.get("mean") and cfg.get("std"):
        mean = np.array(cfg["mean"], dtype=np.float32).reshape((1,1,3))
        std = np.array(cfg["std"], dtype=np.float32).reshape((1,1,3))
        arr = (arr - mean) / std
    if cfg.get("transpose") == "channels_first":
        arr = np.transpose(arr, (2,0,1))
    return arr

# Tiny benchmarking helpers
def time_inference_tf(session_or_model, input_data, is_tflite=False):
    # input_data: numpy array(s) or list
    if is_tflite:
        interpreter = session_or_model
        input_details = interpreter.get_input_details()
        output_details = interpreter.get_output_details()
        interpreter.set_tensor(input_details[0]['index'], input_data.astype(input_details[0]['dtype']))
        t0 = time.time()
        interpreter.invoke()
        t1 = time.time()
        out = interpreter.get_tensor(output_details[0]['index'])
        return (t1-t0), out
    else:
        model = session_or_model
        t0 = time.time()
        out = model.predict(np.expand_dims(input_data, axis=0))
        t1 = time.time()
        return (t1-t0), out

def time_inference_onnx(session, input_data):
    # input_data: numpy array (single)
    input_name = session.get_inputs()[0].name
    t0 = time.time()
    out = session.run(None, {input_name: np.expand_dims(input_data, axis=0)})
    t1 = time.time()
    return (t1-t0), out

# Deploy bundle generator
def create_deploy_bundle(tmp_dir, model_path, preprocessing_cfg, target="generic", model_format="tflite"):
    """
    Produces a zipfile path containing:
      - model file
      - preprocess.json
      - README with instructions
      - example embedded code (MicroPython and C++ stub)
    """
    bundle_dir = Path(tmp_dir) / "deploy_bundle"
    if bundle_dir.exists():
        shutil.rmtree(bundle_dir)
    bundle_dir.mkdir(parents=True)

    # copy model
    model_dst = bundle_dir / Path(model_path).name
    shutil.copy(model_path, model_dst)

    # write preprocessing config
    (bundle_dir / "preprocess.json").write_text(json.dumps(preprocessing_cfg, indent=2))

    # write README
    readme = f"""
Embedded AI Deploy Bundle
=========================

Target: {target}
Model: {model_dst.name}
Model format: {model_format}

Files:
 - {model_dst.name} : model binary for device
 - preprocess.json : JSON config used by host/device to pre-process sensor input
 - device_stub.py : MicroPython/embedded Python inference stub
 - device_stub.cpp : C++ inference stub (conceptual)

Usage:
 1. Copy the model file to your device storage or flash it as part of firmware.
 2. Implement input preprocessing that follows preprocess.json (resize, scale, mean/std, channel order).
 3. Load model into your device's inference runtime (TFLite Micro, ONNX micro, or vendor SDK).
 4. Run inference with preprocessed input. See device_stub.* for sample code.

Notes:
 - For INT8 quantized models, ensure the device runtime supports the quantized ops.
 - You may need to optimize model ops or use vendor-specific quantized kernels.
"""
    (bundle_dir / "README.txt").write_text(readme)

    # MicroPython/Python stub (simple)
    device_py = f'''# device_stub.py - MicroPython / Embedded Python example
# This is a minimal example showing how to load an interpreted model and run inference.
# On microcontrollers you would use TFLite Micro API in C/C++; this Python stub is for prototyping.

MODEL_FILENAME = "{model_dst.name}"
PREPROCESS_CFG = {json.dumps(preprocessing_cfg, indent=2)}

def preprocess_image_bytes(image_bytes):
    # device-side implementation depends on hardware. Here we mirror host-side pipeline.
    from PIL import Image
    import numpy as np
    im = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    # Apply resize & scale in PREPROCESS_CFG...
    # Implement device-specific transforms here.
    return np.zeros((1, PREPROCESS_CFG.get("resize",[1,1])[0], PREPROCESS_CFG.get("resize",[1,1])[1], 3), dtype='float32')

def main():
    # Pseudocode:
    # 1) read sensor/camera bytes
    # 2) preprocess with preprocess_image_bytes
    # 3) load model and run inference
    # For microcontrollers use vendor SDK / TF Micro C++ example.

    print("This is a prototype stub. Adapt for your target device (TFLite Micro, ONNX Micro, etc).")
'''
    (bundle_dir / "device_stub.py").write_text(device_py)

    # C++ stub (conceptual)
    device_cpp = f'''// device_stub.cpp - conceptual C++ stub for embedded devices
// This is a minimal conceptual example; adapt to your runtime (TFLite Micro, CMSIS-NN, vendor SDK)
//
// Load model: {model_dst.name}
// Preprocess: follow preprocess.json
//
// Example using pseudo-APIs:
#include <cstdio>
int main() {{
    // 1) load model bytes from flash
    // 2) decode sensor data and preprocess (resize, normalize)
    // 3) run inference using TFLite Micro or other runtime
    printf("Adapt this stub to your platform and build system.\\n");
    return 0;
}}
'''
    (bundle_dir / "device_stub.cpp").write_text(device_cpp)

    # ZIP it
    zip_path = Path(tmp_dir) / "deploy_bundle.zip"
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as z:
        for f in bundle_dir.iterdir():
            z.write(f, arcname=f.name)
    return str(zip_path)

# Streamlit UI
st.title("Embedded AI — Optimize & Deploy")
st.markdown("A single-file Streamlit app to help you prototype optimizing and deploying AI models to embedded devices. Upload a model, optionally a sample dataset, configure preprocessing, run quick optimizations (if libs available), benchmark, and produce a deploy bundle.")

col1, col2 = st.columns([1,2])

with col1:
    st.header("1) Model & Data")
    model_file = st.file_uploader("Upload model (.tflite, .onnx, SavedModel .zip/.tar/.dir, .h5)", type=['tflite','onnx','h5','zip','tar','pb','savedmodel'])
    sample_images = st.file_uploader("Upload sample images (zip) — used for representative dataset / benchmarking", type=['zip','png','jpg','jpeg'], accept_multiple_files=False)
    sample_csv = st.file_uploader("Upload sample CSV (tabular sensor data) for preprocessing", type=['csv','txt'], accept_multiple_files=False)
    sample_wav = st.file_uploader("Upload sample WAV (audio) for preprocessing", type=['wav'], accept_multiple_files=False)

    st.write("Simulated Data Acquisition")
    sim_source = st.radio("Acquire data from:", ["Upload files", "Simulate serial sensor (mock)"])
    if sim_source == "Simulate serial sensor (mock)":
        st.info("Mock serial stream will be simulated; to connect a real serial port, integrate pyserial on your host and adapt device code.")
        simulate_rate = st.slider("Simulate samples per second", 1, 60, 5)

with col2:
    st.header("2) Preprocessing pipeline")
    st.markdown("Configure how raw sensor/image/audio data should be transformed before inference. Save to `preprocess.json` in the deploy bundle.")
    preprocess = {}
    st.write("Image preprocessing (for vision models)")
    want_image_pre = st.checkbox("Enable image preprocessing", value=True)
    if want_image_pre:
        resize_h = st.number_input("Resize height", min_value=1, value=224)
        resize_w = st.number_input("Resize width", min_value=1, value=224)
        scale = st.selectbox("Pixel scaling", options=["1/255", "none"], index=0)
        scale_val = "1/255" if scale=="1/255" else "1.0"
        channel_order = st.selectbox("Channel order", ["channels_last (HWC)", "channels_first (CHW)"], index=0)
        mean_spec = st.text_input("Mean (comma separated) - leave blank for none", value="127.5,127.5,127.5")
        std_spec = st.text_input("Std (comma separated) - leave blank for none", value="127.5,127.5,127.5")
        transpose = "channels_first" if channel_order.startswith("channels_first") else "channels_last"

        preprocess["image"] = {
            "resize": [int(resize_h), int(resize_w)],
            "scale": float(1.0/255.0) if scale_val=="1/255" else 1.0,
            "mean": [float(x.strip()) for x in mean_spec.split(",")] if mean_spec else None,
            "std": [float(x.strip()) for x in std_spec.split(",")] if std_spec else None,
            "transpose": transpose
        }

    st.write("Tabular preprocessing (for sensor data)")
    want_tab = st.checkbox("Enable tabular preprocessing", value=False)
    if want_tab:
        tab_norm = st.selectbox("Scale numeric columns", ["minmax", "standard", "none"], index=2)
        preprocess["tabular"] = {"scaling": tab_norm}

    st.write("Audio preprocessing")
    want_audio = st.checkbox("Enable audio preprocessing", value=False)
    if want_audio:
        sample_rate = st.number_input("Target sample rate", value=16000)
        n_mels = st.number_input("Number of mel bins", value=40)
        preprocess["audio"] = {"sample_rate": int(sample_rate), "n_mels": int(n_mels)}

st.markdown("---")
st.header("3) Optimization & Conversion")
st.write("Pick a target format and optimization strategy. The app will try to run conversions if supporting libraries are installed on the host.")

col3, col4 = st.columns(2)
with col3:
    target_format = st.selectbox("Target model format", ["tflite", "onnx", "keep original"])
    opt_quant = st.selectbox("Quantization strategy", ["none", "float16", "int8 (requires representative dataset & TF)"], index=0)
    opt_prune = st.checkbox("Prune model (conceptual; requires training toolchain)", value=False)
with col4:
    st.write("Available toolkits detection:")
    st.write(f"TensorFlow available: {'✅' if TF_AVAILABLE else '❌'}")
    st.write(f"ONNX + ONNX Runtime available: {'✅' if ONNX_AVAILABLE else '❌'}")
    st.write("Note: Full INT8 conversion usually requires TensorFlow and a representative dataset (uploaded sample images).")

# Processing actions
st.markdown("---")
st.header("Actions")

tmpdir = tempfile.mkdtemp(prefix="embed_ai_")
model_saved_path = None
if model_file:
    model_saved_path = save_uploaded_file(model_file, tmpdir)
    st.success(f"Model saved to: {model_saved_path} ({bytes_to_human(os.path.getsize(model_saved_path))})")

# Conversion buttons
col_a, col_b, col_c = st.columns(3)

conversion_result = None
if col_a.button("Run conversion/optimization"):
    if not model_saved_path:
        st.error("Upload a model first.")
    else:
        with st.spinner("Running conversion/optimization..."):
            out_msgs = []
            out_model_path = model_saved_path
            model_name = Path(model_saved_path).name.lower()
            # If user wants tflite and TF available:
            if target_format == "tflite":
                if TF_AVAILABLE:
                    try:
                        # If uploaded already a .tflite, skip conversion
                        if model_name.endswith(".tflite"):
                            out_msgs.append("Uploaded model is already .tflite; skipping conversion.")
                            out_model_path = model_saved_path
                        else:
                            # Try conversion using TF APIs. Support .h5 and SavedModel zipped
                            if model_name.endswith(".h5") or model_name.endswith(".keras"):
                                model = tf.keras.models.load_model(model_saved_path)
                                converter = tf.lite.TFLiteConverter.from_keras_model(model)
                            elif model_name.endswith(".zip") or model_name.endswith(".tar") or model_name.endswith(".savedmodel") or os.path.isdir(model_saved_path):
                                # Try SavedModel folder
                                try:
                                    converter = tf.lite.TFLiteConverter.from_saved_model(model_saved_path)
                                except Exception as e:
                                    # try load keras
                                    model = tf.keras.models.load_model(model_saved_path)
                                    converter = tf.lite.TFLiteConverter.from_keras_model(model)
                            else:
                                # last resort: try load as keras
                                model = tf.keras.models.load_model(model_saved_path)
                                converter = tf.lite.TFLiteConverter.from_keras_model(model)
                            # Apply quantization options
                            if opt_quant == "float16":
                                converter.optimizations = [tf.lite.Optimize.DEFAULT]
                                converter.target_spec.supported_types = [tf.float16]
                                out_msgs.append("Applying float16 quantization.")
                            elif opt_quant == "int8":
                                if not sample_images:
                                    st.warning("INT8 quantization selected but no representative dataset uploaded. Upload sample images (zip) for representative data.")
                                else:
                                    converter.optimizations = [tf.lite.Optimize.DEFAULT]
                                    # representative dataset function
                                    def representative_gen():
                                        # attempt to read a few images from uploaded zip
                                        import zipfile
                                        z = zipfile.ZipFile(sample_images)
                                        names = [n for n in z.namelist() if n.lower().endswith(('.png','.jpg','.jpeg'))][:50]
                                        for name in names:
                                            b = z.read(name)
                                            arr = read_image_bytes_to_array(b)
                                            arr = apply_preprocessing(arr, preprocess.get("image", {"resize":[224,224],"scale":1/255.0}))
                                            yield [np.expand_dims(arr.astype(np.float32), axis=0)]
                                        return
                                    try:
                                        converter.representative_dataset = representative_gen
                                        out_msgs.append("Configured representative dataset for INT8 conversion (host-side).")
                                    except Exception as e:
                                        out_msgs.append(f"Warning: failed to set representative_dataset: {e}")
                            tflite_model = converter.convert()
                            out_model_path = str(Path(tmpdir) / (Path(model_saved_path).stem + ".tflite"))
                            with open(out_model_path, "wb") as f:
                                f.write(tflite_model)
                            out_msgs.append(f"Converted to TFLite: {out_model_path}")
                    except Exception as e:
                        out_msgs.append("TFLite conversion failed: " + str(e))
                else:
                    out_msgs.append("TensorFlow not available; cannot convert to TFLite.")
            elif target_format == "onnx":
                if ONNX_AVAILABLE:
                    # Converting from keras to onnx would require tf2onnx or similar; we will attempt a simple path if possible
                    try:
                        if model_name.endswith(".onnx"):
                            out_msgs.append("Uploaded model already ONNX; skipping conversion.")
                            out_model_path = model_saved_path
                        else:
                            # try tf -> onnx via tf2onnx if available
                            try:
                                import tf2onnx
                                if model_name.endswith(".h5") or model_name.endswith(".keras"):
                                    keras_model = tf.keras.models.load_model(model_saved_path)
                                    spec = (tf.TensorSpec(keras_model.inputs[0].shape, tf.float32, name="input"),)
                                    model_proto, _ = tf2onnx.convert.from_keras(keras_model, input_signature=spec, opset=13)
                                    onnx_path = str(Path(tmpdir) / (Path(model_saved_path).stem + ".onnx"))
                                    with open(onnx_path, "wb") as f:
                                        f.write(model_proto.SerializeToString())
                                    out_model_path = onnx_path
                                    out_msgs.append(f"Converted Keras -> ONNX via tf2onnx: {onnx_path}")
                                else:
                                    out_msgs.append("ONNX conversion: uploaded model not supported for auto-conversion (host toolbox required).")
                            except Exception as e:
                                out_msgs.append("tf2onnx not installed or conversion failed: " + str(e))
                    except Exception as e:
                        out_msgs.append("ONNX conversion failed: " + str(e))
                else:
                    out_msgs.append("ONNX runtime not available; cannot convert.")
            else:
                out_msgs.append("Keeping original model format.")

            conversion_result = {"msgs": out_msgs, "out_model": out_model_path}
            st.success("Conversion/optimization process complete.")
            for m in out_msgs:
                st.write("-", m)

# Benchmarking
st.markdown("---")
st.header("4) Quick Benchmark")

bench_result = None
if st.button("Run simple benchmark"):
    if not model_saved_path:
        st.error("Upload/convert a model first.")
    else:
        st.info("This benchmark uses sample inputs, does not replace full profiling on hardware.")
        # Prepare sample input
        sample_input = None
        if sample_images:
            # if zip, take first image from zip
            import zipfile
            try:
                zipf = zipfile.ZipFile(sample_images)
                names = [n for n in zipf.namelist() if n.lower().endswith(('.png','.jpg','.jpeg'))]
                if names:
                    b = zipf.read(names[0])
                    arr = read_image_bytes_to_array(b)
                    sample_input = apply_preprocessing(arr, preprocess.get("image", {"resize":[224,224],"scale":1/255.0}))
                else:
                    st.warning("No images found in the zip; using a random tensor.")
            except Exception as e:
                st.warning("Failed to read zip; using random tensor.")
        if sample_input is None:
            # fallback: random input using image preprocess dims or [224,224,3]
            dims = preprocess.get("image", {}).get("resize", [224,224])
            cdim = 3
            sample_input = np.random.randint(0,255,(dims[0],dims[1],cdim)).astype(np.uint8)
            sample_input = apply_preprocessing(sample_input, preprocess.get("image", {"resize":[dims[0],dims[1]], "scale":1/255.0}))
        # Determine model type and run inference time
        model_name = Path(model_saved_path).name.lower()
        bench_records = {}
        try:
            if model_name.endswith(".tflite") or (conversion_result and conversion_result.get("out_model", "").endswith(".tflite")):
                tpath = conversion_result.get("out_model", model_saved_path)
                try:
                    import tensorflow as tf
                    interpreter = tf.lite.Interpreter(model_path=tpath)
                    interpreter.allocate_tensors()
                    # run a few inferences
                    times = []
                    for _ in range(5):
                        t, _ = time_inference_tf(interpreter, sample_input, is_tflite=True)
                        times.append(t)
                    bench_records["runtime"] = "tflite-interpreter (host)"
                    bench_records["times"] = times
                    bench_records["median_ms"] = float(np.median(times))*1000.0
                except Exception as e:
                    st.warning("Host TFLite interpreter not available: " + str(e))
            elif model_name.endswith(".onnx") or (conversion_result and conversion_result.get("out_model","").endswith(".onnx")):
                try:
                    import onnxruntime as ort
                    onnx_path = conversion_result.get("out_model", model_saved_path)
                    sess = ort.InferenceSession(onnx_path, providers=['CPUExecutionProvider'])
                    times = []
                    for _ in range(5):
                        t, _ = time_inference_onnx(sess, sample_input.astype(np.float32))
                        times.append(t)
                    bench_records["runtime"] = "onnxruntime (host)"
                    bench_records["times"] = times
                    bench_records["median_ms"] = float(np.median(times))*1000.0
                except Exception as e:
                    st.warning("ONNX runtime not available on host: " + str(e))
            else:
                # try TF keras predict
                if TF_AVAILABLE:
                    try:
                        model = tf.keras.models.load_model(model_saved_path)
                        times = []
                        for _ in range(5):
                            t, _ = time_inference_tf(model, sample_input, is_tflite=False)
                            times.append(t)
                        bench_records["runtime"] = "tf.keras (host)"
                        bench_records["times"] = times
                        bench_records["median_ms"] = float(np.median(times))*1000.0
                    except Exception as e:
                        st.warning("Failed to load model with tensorflow.keras: " + str(e))
                else:
                    st.warning("No supported runtime available on host to benchmark model.")
        except Exception as e:
            st.error("Benchmark failed: " + str(e))
        bench_result = bench_records
        if bench_result:
            st.write("Benchmark results:")
            st.write(bench_result)

# Deploy bundle
st.markdown("---")
st.header("5) Create deploy bundle")
target_device = st.selectbox("Target device/stack", ["generic", "tflite-micro (C++)", "micropython", "raspberry-pi (Linux)"])
if st.button("Create deploy bundle"):
    if not model_saved_path:
        st.error("No model present.")
    else:
        model_to_package = conversion_result.get("out_model", model_saved_path) if conversion_result else model_saved_path
        st.info("Generating bundle...")
        zip_path = create_deploy_bundle(tmpdir, model_to_package, preprocess.get("image",{}), target=target_device, model_format=target_format)
        st.success(f"Created deploy bundle: {zip_path} ({bytes_to_human(os.path.getsize(zip_path))})")
        with open(zip_path, "rb") as f:
            b = f.read()
            st.download_button("Download bundle (zip)", data=b, file_name="deploy_bundle.zip", mime="application/zip")

st.markdown("---")
st.header("6) Helpful tips & next steps")
st.markdown("""
- For **TFLite Micro** deployment: follow TensorFlow Lite Micro's guide to integrate the `.tflite` file into your MCU firmware as a C array and use the TFLite Micro interpreter.
- For **INT8** quantization: you must provide a representative dataset; conversion should be validated for accuracy on host before deploying to device.
- For **ONNX -> Embedded**: many microcontrollers don't support ONNX natively; use vendor runtimes or convert to TFLite for microcontrollers.
- For **communication**: use UART/SPI/I2C for raw sensor data. For remote devices, use MQTT over TLS (if device supports it) or an edge gateway.
""")

st.markdown("## Quick embedded code examples")
st.code("""// Example: Print model info on device (C++)
// - Load model bytes, report size. Implement preprocessing per preprocess.json
#include <cstdio>
#include <fstream>
int main() {
    std::ifstream f("model.tflite", std::ios::binary | std::ios::ate);
    if (!f) { printf("model not found\\n"); return 1; }
    auto size = f.tellg();
    printf("Model size: %lld bytes\\n", (long long)size);
    // Load into runtime...
    return 0;
}
""", language="cpp")

st.markdown("---")
st.caption("This UI is a prototyping tool. For production embedded deployment you will need to adapt code to your device SDK, toolchain, and confirm quantized ops/runtime compatibility.")

# Cleanup tmpdir on exit? We leave temp files so user can inspect; could remove in production.